### ISSUE TITLE
Serialization support

### ISSUE THREAD

**Issue by paulosuzart** [rust-lang/time#91]
Hi,

Is there any plan to have full rustc-serialize support for the whole lib? Using `time::Timespec` forced me to use custom Json mapping instead of simply annotate my struct with `RustcEncoable`.

Thanks

**Comment by alexcrichton** [comment]
Support for `rustc-serialize` is actually an [optional feature](https://github.com/rust-lang/time/blob/master/Cargo.toml#L17) of this library, so you should be able to depend on it like so:

```toml
[dependencies]
time = { version = "...", features = ["rustc-serialize"] }
```

And that should do the trick!
